### ISSUE TITLE
Error stopping node: TypeError: Cannot read property 'disconnect' of undefined

### ISSUE THREAD

**Issue by jdockter** [hyperledger/composer-tools#135]
After installing latest node-red-contrib-composer node I'm getting the following error when I try to deploy after putting composer-out node into a flow:

25 May 13:09:57 - [debug] red/nodes/flows.stop : stopping flow : 140a86d5.8f85b9
25 May 13:09:57 - [trace] Stopping node inject:b64922ff.1745
25 May 13:09:57 - [trace] Stopping node debug:2f455e04.e40ac2
25 May 13:09:57 - [trace] Stopping node hyperledger-composer-out:b9dcefc.e087b1
25 May 13:09:57 - [trace] Stopped node inject:b64922ff.1745 (1ms)
25 May 13:09:57 - [trace] Stopped node debug:2f455e04.e40ac2 (2ms)
25 May 13:09:57 - [error] [hyperledger-composer-out:Local] Error stopping node: TypeError: Cannot read property 'disconnect' of undefined
25 May 13:09:57 - [debug] TypeError: Cannot read property 'disconnect' of undefined
    at HyperledgerComposerOutNode.node.on (/home/ibm/.node-red/node_modules/node-red-contrib-composer/nodes/hyperledger-composer.js:457:43)
    at HyperledgerComposerOutNode.Node.close (/home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/node-red/red/runtime/nodes/Node.js:102:22)
    at /home/ibm/.nvm/versions/node/v8.9.0/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:166:47

**Comment by jdockter** [comment]
@caroline-church see above error

**Comment by jdockter** [comment]
local composer info:
$ composer -v
v0.19.5

node-red version info:
25 May 13:39:59 - [info] Node-RED version: v0.18.6
25 May 13:39:59 - [info] Node.js  version: v8.9.0
25 May 13:39:59 - [info] Linux 4.13.0-43-generic x64 LE
25 May 13:40:00 - [info] Loading palette nodes
