### ISSUE TITLE
Failed to build fabric-scripts/hlfv11/composer/howtobuild.txt

### ISSUE THREAD

**Issue by ywandy** [hyperledger/composer-tools#138]
I just follow this txt ,but i failed when i exec ```configtxgen -profile ComposerOrdererGenesis -outputBlock ./composer-genesis.block ```  

How can i due with it

This is my error output:
```
# yewei @ xinou-work in ~/code/composer-proj/fds/fabric-scripts/hlfv11/composer [17:38:36]
$ configtxgen -profile ComposerOrdererGenesis -outputBlock ./composer-genesis.block
2018-07-31 17:38:41.170 CST [common/tools/configtxgen] main -> WARN 001 Omitting the channel ID for configtxgen is deprecated.  Explicitly passing the channel ID will be required in the future, defaulting to 'testchainid'.
2018-07-31 17:38:41.170 CST [common/tools/configtxgen] main -> INFO 002 Loading configuration
2018-07-31 17:38:41.170 CST [common/tools/configtxgen/localconfig] Load -> CRIT 003 Error reading configuration:  While parsing config: yaml: unknown anchor 'OrdererDefaults' referenced
2018-07-31 17:38:41.170 CST [common/tools/configtxgen] func1 -> CRIT 004 Error reading configuration: While parsing config: yaml: unknown anchor 'OrdererDefaults' referenced
panic: Error reading configuration: While parsing config: yaml: unknown anchor 'OrdererDefaults' referenced [recovered]
        panic: Error reading configuration: While parsing config: yaml: unknown anchor 'OrdererDefaults' referenced

goroutine 1 [running]:
github.com/hyperledger/fabric/vendor/github.com/op/go-logging.(*Logger).Panic(0xc4201cbe00, 0xc4203ea4e0, 0x1, 0x1)
        /w/workspace/fabric-nightly-release-job-release-1.2-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/github.com/op/go-logging/logger.go:188 +0xbd
main.main.func1()
        /w/workspace/fabric-nightly-release-job-release-1.2-x86_64/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:254 +0x1ae
panic(0xc6ea00, 0xc4203ea4d0)
        /opt/go/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
github.com/hyperledger/fabric/vendor/github.com/op/go-logging.(*Logger).Panic(0xc4201cbc50, 0xc420492ae0, 0x2, 0x2)
        /w/workspace/fabric-nightly-release-job-release-1.2-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/github.com/op/go-logging/logger.go:188 +0xbd
github.com/hyperledger/fabric/common/tools/configtxgen/localconfig.Load(0x7fffbed3860f, 0x16, 0x0, 0x0, 0x0, 0x1)
        /w/workspace/fabric-nightly-release-job-release-1.2-x86_64/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/localconfig/config.go:277 +0x469
main.main()
        /w/workspace/fabric-nightly-release-job-release-1.2-x86_64/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:265 +0xce7
```

**Comment by ywandy** [comment]
I solve it！
just move the code which in fabric-scripts/hlfv11/composer/configtx.yaml to the end of this yaml
the code:
```
Profiles:

    ComposerOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            ComposerConsortium:
                Organizations:
                    - *Org1
    ComposerChannel:
        Consortium: ComposerConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
```

**Comment by davidkel** [comment]
closing as resolved.

**Comment by hingjlee** [comment]
that's useful info. even though I can generate the Genesis block, i get tons of warnings. 

`
2018-09-01 22:34:57.111 UTC [common/tools/configtxgen] main -> WARN 001 Omitting the channel ID for configtxgen is deprecated.  Explicitly passing the channel ID will be required in the future, defaulting to 'testchainid'.
2018-09-01 22:34:57.111 UTC [common/tools/configtxgen] main -> INFO 002 Loading configuration
2018-09-01 22:34:57.117 UTC [common/tools/configtxgen/encoder] NewChannelGroup -> WARN 003 Default policy emission is deprecated, please include policy specificiations for the channel group in configtx.yaml
2018-09-01 22:34:57.117 UTC [common/tools/configtxgen/encoder] NewOrdererGroup -> WARN 004 Default policy emission is deprecated, please include policy specificiations for the orderer group in configtx.yaml
2018-09-01 22:34:57.120 UTC [common/tools/configtxgen/encoder] NewOrdererOrgGroup -> WARN 005 Default policy emission is deprecated, please include policy specificiations for the orderer org group OrdererOrg in configtx.yaml
2018-09-01 22:34:57.120 UTC [common/tools/configtxgen/encoder] addSignaturePolicyDefaults -> WARN 006 Specifying AdminPrincipal is deprecated and will be removed in a future release, override the admin principal with explicit policies.
2018-09-01 22:34:57.121 UTC [common/tools/configtxgen/encoder] NewOrdererOrgGroup -> WARN 007 Default policy emission is deprecated, please include policy specificiations for the orderer org group 300cubits in configtx.yaml
2018-09-01 22:34:57.121 UTC [common/tools/configtxgen/encoder] addSignaturePolicyDefaults -> WARN 008 Specifying AdminPrincipal is deprecated and will be removed in a future release, override the admin principal with explicit policies.
2018-09-01 22:34:57.121 UTC [common/tools/configtxgen] doOutputBlock -> INFO 009 Generating genesis block
2018-09-01 22:34:57.122 UTC [common/tools/configtxgen] doOutputBlock -> INFO 00a Writing genesis block
`

**Comment by rakhaagung16** [comment]
Hi @ywandy ,
thank you for your step and I've tried but find some errors:

    2018-09-09 09:30:16.595 UTC [msp] setupSigningIdentity -> DEBU 035 Signing identity expires at 2027-06-24 12:49:26 +0000 UTC
    2018-09-09 09:30:16.595 UTC [msp] Validate -> DEBU 036 MSP Org1MSP validating identity
    2018-09-09 09:30:16.595 UTC [msp] GetDefaultSigningIdentity -> DEBU 037 Obtaining default signing identity
    2018-09-09 09:30:16.596 UTC [grpc] Printf -> DEBU 038 parsed scheme: ""
    2018-09-09 09:30:16.596 UTC [grpc] Printf -> DEBU 039 scheme "" not registered, fallback to default scheme
    2018-09-09 09:30:16.596 UTC [grpc] Printf -> DEBU 03a ccResolverWrapper: sending new addresses to cc: [{orderer.example.com:7050 0  <nil>}]
    2018-09-09 09:30:16.596 UTC [grpc] Printf -> DEBU 03b ClientConn switching balancer to "pick_first"
    2018-09-09 09:30:16.596 UTC [grpc] Printf -> DEBU 03c pickfirstBalancer: HandleSubConnStateChange: 0xc42021c4f0, CONNECTING
    **Error: failed to create deliver client: orderer client failed to connect to orderer.example.com:7050: failed to create new connection: context deadline exceeded**

my environment:
Composer: 0.20
Fabric: 1.2.0
Couchdb: 0.4.0
I've pulled my env from https://hyperledger-fabric.readthedocs.io/en/release-1.2/install.html
and I've followed https://medium.com/hyperlegendary/setting-up-a-blockchain-business-network-with-hyperledger-fabric-composer-running-in-multiple-bfbe4e38b6c6 as my main tutorial

Thank you for your time, @ywandy
