### ISSUE TITLE
createPeerAdminCard.sh No version of composer-cli has been detected

### ISSUE THREAD

**Issue by siddjain** [hyperledger/composer-tools#153]
Hello,

I am getting started with HL Fabric. I get this error while trying to run createPeerAdminCard.sh. can anyone help me?

```
$ ./createPeerAdminCard.sh 
Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is unset, assuming hlfv12
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)

No version of composer-cli has been detected, you need to install composer-cli at v0.20 or higher

```

Further info to help in debugging:

```
$ ls /usr/lib/node_modules/
composer-cli         composer-rest-server            gulp  yo
composer-playground  generator-hyperledger-composer  npm
```

```
$ composer --help
/usr/lib/node_modules/composer-cli/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/composer-cli/node_modules/composer-common/index.js:56:43)
```

**Comment by siddjain** [comment]
solution to this problem is to upgrade node to version 8.9 or higher but below version 9
the async keyword was added to node only in version 8
steps to upgrade node are documented in https://www.hostingadvice.com/how-to/update-node-js-latest-version/
if using
```
sudo npm cache clean -f
sudo npm install -g n
sudo n 8.9
```
make sure to also run
```
sudo ln -sf /usr/local/n/versions/node/<version>/bin/node /usr/bin/node
```

**Comment by nileshbhoskar** [comment]
Hi Siddjain,

I spend around 2 days on this but still this issue not get resolved for me.
my node version is 8.14, so should I need to downgrade it to 8.9?

Below is log received after execution.

Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is set to 'hlfv12'
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)

No version of composer-cli has been detected, you need to install composer-cli at v0.20 or higher

**Comment by siddjain** [comment]
Are you sure you have composer installed?
No version of composer-cli has been detected, you need to install composer-cli at v0.20 or higher

Do you see any more error message(s)?

What do you see if you run

composer --help

________________________________

**Comment by nirdesh27** [comment]
I am also having this issue, I had installed the composer-cli as:
npm install composer-cli --save   
I don't use -g (global) is this an issue with ?

Please suggest

**Comment by nirdesh27** [comment]
composer --help give me the following results:

```
module.js:557
    throw err;
    ^

Error: Cannot find module './api'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/composer-cli/node_modules/node-report/index.js:3:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

```
